import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import { UpMenu } from '@/components/upMenu'
import { ModeToggle } from '@/components/modeToggle'
import { Toaster } from '@/components/ui/toaster'

import { Button, Breadcrumbs, BreadcrumbItem } from '@nextui-org/react'

// const inter = Inter({ subsets: ['latin'] })
export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      {/* <body className={inter.className}> */}
      {/* <header>
      </header> */}
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <UpMenu />

          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
